## Base

In [8]:
import numpy as np
import pandas as pd

In [9]:
a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])


## Dot product

In [10]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

### Nut butter sales

In [11]:
np.random.seed(0)

# Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [26]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts, 
                           index=["Mon", "Tues","Wed", "Thurs", "Fri"],
                           columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [27]:
# Create prices array 
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [14]:
prices.shape

(3,)

In [28]:
prices.shape

(3,)

In [29]:
# prices must be reshaped
butter_prices = pd.DataFrame(prices.reshape(1, 3), 
                            index=["Price"], 
                            columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [30]:
# Align shapes to get total 

total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [31]:
# Create daily_sales
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [19]:
weekly_sales.T.shape

(3, 5)

In [20]:
butter_prices.shape, weekly_sales.T.shape

((1, 3), (3, 5))

In [32]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [33]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [38]:
daily_sales.shape, weekly_sales.shape

((1, 5), (5, 4))

In [36]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142