## Maniputlating & Comparing Arrays

In [4]:
import numpy as np

In [5]:
# One dimensional array (vector)

a1 = np.array([1, 2, 3])

In [6]:
#  multi-dimensional arrys (matrices)
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
# See the number of dimensions (.ndim)
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [ ]:
# Ones & Zeros returns a new array of a given shape filled with 1s or 0s 
# These can be used as placeholders

zeros = np.zeros((2,3))
ones = np.ones((2,3))

In [1]:
## Find unique elements of an array (np.unique())


### Arithmetic

In [12]:
a1

array([1, 2, 3])

In [13]:
ones1 = np.ones(3)
ones1

array([1., 1., 1.])

In [14]:
a1 + ones1

array([2., 3., 4.])

In [15]:
a1 - ones1

array([0., 1., 2.])

In [16]:
a1 * ones1

array([1., 2., 3.])

In [18]:
a1

array([1, 2, 3])

In [19]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [17]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [20]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [21]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [22]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 