## Base

In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])


## Reshaping & Transposing 

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [13]:
# If the shape of 2 arrays are equal broadcasting can happen 
# If not equal then one of the arrays has to be 1
# Add a dimension 

a2.reshape(2, 3, 1).shape

(2, 3, 1)

In [14]:
a3.shape

(2, 3, 3)

In [15]:
a2_reshape = a2.reshape(2, 3, 1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [16]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [19]:
a2.shape

(2, 3)

In [18]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [17]:
# Transpose 

a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [20]:
a2.T.shape

(3, 2)

In [21]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])